spring:
  datasource:
    username: root
    password: nAvi@7799
    url: jdbc:mysql://localhost:3306/jrtp
    driver: com.mysql.cj.jdbc.driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9077
    
plan-api:
  messages:
    planSaveSucc: Plan Saved Succesfully
    planSaveFail: Plan Save Failed
    planUpdateSucc: Plan Updated Successfully
    planUpdateFail: Plan Update Failed
    planDeleteSucc: Plan Deleted Successfully
    planDeleteFail: Plan Delete Failed
    planStatusChange: Plan Status Changed Successfully
    planStatusChangeFail: Plan Status Change Failed