spring:
  datasource:
    username: root
    password: nAvi@7799
    url: jdbc:mysql://localhost:3306/jrtp
    driver: com.mysql.cj.jdbc.driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail: 
    host: smtp.gmail.com
    port: 587
    username: naveenkumarjadi2005@gmail.com
    password: navi@7799
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true